name: Deploy Symfony to SWeb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via Rsync & Execute Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/n/normvoobsh/irlbp/
            
            rsync -avz --delete \
              --exclude='.git/' \
              --exclude='.github/' \
              --exclude='.env.local' \
              --exclude='tests/' \
              ./ ./
            
            /opt/php/81/bin/php bin/console cache:clear --env=prod
            /opt/php/81/bin/php $(which composer) install --no-dev --optimize-autoloader --no-interaction
